//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.29 at 10:48:40 PM COT 
//


package com.arquitectura.users;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.arquitectura.users package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.arquitectura.users
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SuccessResponse }
     * 
     */
    public SuccessResponse createSuccessResponse() {
        return new SuccessResponse();
    }

    /**
     * Create an instance of {@link RegisterClientResponse }
     * 
     */
    public RegisterClientResponse createRegisterClientResponse() {
        return new RegisterClientResponse();
    }

    /**
     * Create an instance of {@link ClientDetails }
     * 
     */
    public ClientDetails createClientDetails() {
        return new ClientDetails();
    }

    /**
     * Create an instance of {@link RegisterClientRequest }
     * 
     */
    public RegisterClientRequest createRegisterClientRequest() {
        return new RegisterClientRequest();
    }

}
